### PR TITLE
Update order.rb

### PR DESCRIPTION
**Pull request by richpeck**
Seems you forgot `packingSlipUrl`, which is required to submit the order.

### CODE REVIEW

**Comment by tomharvey** [comment]
Thanks @richpeck 

Can you clear out the print statements?

Also, if the

**Comment by richpeck** [comment]
That was a hack I used to get the thing to work with Pwinty::Order.list (when one of the orders had an image) - I am still working on getting this resolved. The original merge request is here (seems github has tracked my own personal updates): https://github.com/tomharvey/pwinty3-rb/pull/1/commits/8c8d6dbb837fb9209a8b3dea3339f2f59900a251

**Comment by richpeck** [comment]
Whenever you update an order, without that `packingSlipUrl` line, it fails with an error.

**Comment by tomharvey** [comment]
Ah, the pull request is between your master branch and my master branch. You can see at the top of this page “richpeck wants to merge 7 commits into tomharvey:master from richpeck:master“.

The best thing to do would be to create a branch on your copy of the repo and work on that. The command `git co -b include-packingSlipUrl` will create a branch and set you to work on it. Get that branch to a state where it just includes the change you want to make now. Then, commit `git commit -am”include the packing slip attribute and nothing else”` and then push those changes with `git push -u origin packingSlipUrl`. Finally, create a new pull request which requests the merge of that branch.

The git commands are just examples; if you’ve got your own way to do this; go for it. Just thought I’d include to be helpful; sorry if I’m teaching you to suck eggs. Thanks for the PR.

**Comment by richpeck** [comment]
Will do that momentarily -- regarding the commented out "image" section, I'll do another PR if  find the fix for that

**Comment by tomharvey** [comment]
Thanks for the new PR.

If you can raise an issue describing the issue you’re a trying to fix when listing orders with images I’ll have a look to see if I can help.

**Pull request closed without merging**
